import { College } from './types'

export const colleges: College[] = [
  {
    id: 'iit-kanpur',
    name: 'IIT Kanpur',
    location: 'Kalyanpur, Kanpur',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    fees: 200000,
    rating: 4.9,
    placementRate: 92,
    placementAverage: 2500000,
    placementHighest: 75000000,
    courses: ['B.Tech', 'M.Tech', 'MSc', 'PhD'],
    overview: 'Indian Institute of Technology Kanpur is a premier technical institute known for strong research programs, excellent faculty, and outstanding placement records. Established in 1959, IIT Kanpur has consistently ranked among the top engineering institutes in India.',
    image: '/images/colleges/iit-kanpur.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Iit Kanpur campus (CC BY-SA)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1959,
    ranking: { nirf: 4, outlook: 3, times: 5, collegedunia: 2 },
    cutoffs: [
      { exam: 'JEE-Advanced', year: 2025, round: 1, score: 245 },
      { exam: 'JEE-Advanced', year: 2024, round: 1, score: 238 },
    ],
    facilities: ['Central Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Incubation Center', 'Cafeteria'],
    contact: { phone: '+91-512-2590151', email: 'info@iitk.ac.in', website: 'iitk.ac.in' },
    reviews: [
      { name: 'Arun S.', rating: 5, comment: 'Excellent faculty and research opportunities. The campus life is vibrant.', date: '2025-12-10' },
      { name: 'Priya M.', rating: 5, comment: 'World-class infrastructure and placement opportunities.', date: '2025-11-20' },
    ],
    gallery: ['https://images.unsplash.com/photo-1541339907198-e08756dedf3f?w=800'],
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Goldman Sachs', 'Tesla', 'Intel', 'Qualcomm', 'McKinsey'],
    campusSize: '1055 acres',
    totalStudents: 8250,
    facultyCount: 620,
    accreditation: 'NAAC A++',
    hostelFees: '₹1,20,000/year',
    courseFees: [
      { name: 'B.Tech', totalFees: '₹8,00,000', duration: '4 Years' },
      { name: 'M.Tech', totalFees: '₹2,80,000', duration: '2 Years' },
      { name: 'MSc', totalFees: '₹1,60,000', duration: '2 Years' },
      { name: 'PhD', totalFees: '₹1,20,000', duration: '5 Years' },
    ],
    importantDates: [
      { event: 'JEE Advanced Application', date: 'April 2026' },
      { event: 'JEE Advanced Exam', date: 'May 2026' },
      { event: 'Counselling Start', date: 'June 2026' },
      { event: 'Classes Begin', date: 'July 2026' },
    ],
    annualEvents: ['Techkriti', 'Antaragni', 'Udghosh'],
    notableAlumni: ['Duvvuri Subbarao (Ex-RBI Governor)', 'Naresh Goyal (Jet Airways Founder)', 'Arvind Krishna (IBM CEO)'],
  },
  {
    id: 'iit-bombay',
    name: 'IIT Bombay',
    location: 'Powai, Mumbai',
    city: 'Mumbai',
    state: 'Maharashtra',
    fees: 220000,
    rating: 4.9,
    placementRate: 94,
    placementAverage: 2800000,
    placementHighest: 80000000,
    courses: ['B.Tech', 'M.Tech', 'MSc', 'PhD'],
    overview: 'IIT Bombay is one of the most prestigious engineering institutes in India, known for its cutting-edge research, excellent faculty, and top-tier placements. Located in Powai, Mumbai, the campus is spread across 550 acres.',
    image: '/images/colleges/iit-bombay.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:IITBMainBuidling.jpg by Arne Hückelheim (CC BY-SA 3.0)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1958,
    ranking: { nirf: 3, outlook: 1, times: 2, collegedunia: 1 },
    facilities: ['Central Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Innovation Hub', 'Student Activity Center'],
    contact: { phone: '+91-22-25722545', email: 'info@iitb.ac.in', website: 'iitb.ac.in' },
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Apple', 'Goldman Sachs', 'BCG', 'McKinsey', 'Texas Instruments'],
    campusSize: '550 acres',
    totalStudents: 10200,
    facultyCount: 750,
    accreditation: 'NAAC A++',
    hostelFees: '₹1,10,000/year',
    courseFees: [
      { name: 'B.Tech', totalFees: '₹8,80,000', duration: '4 Years' },
      { name: 'M.Tech', totalFees: '₹3,00,000', duration: '2 Years' },
      { name: 'MSc', totalFees: '₹1,80,000', duration: '2 Years' },
      { name: 'PhD', totalFees: '₹1,40,000', duration: '5 Years' },
    ],
    importantDates: [
      { event: 'JEE Advanced Application', date: 'April 2026' },
      { event: 'JEE Advanced Exam', date: 'May 2026' },
      { event: 'Counselling Start', date: 'June 2026' },
      { event: 'Classes Begin', date: 'July 2026' },
    ],
    annualEvents: ['Mood Indigo', 'Techfest', 'E-Summit'],
    notableAlumni: ['N. R. Narayana Murthy (Infosys Co-founder)', 'Sundar Pichai (Google CEO)', 'Kumar Mangalam Birla (BITS Chancellor)'],
  },
  {
    id: 'iit-delhi',
    name: 'IIT Delhi',
    location: 'Hauz Khas, New Delhi',
    city: 'Delhi',
    state: 'Delhi',
    fees: 210000,
    rating: 4.8,
    placementRate: 93,
    placementAverage: 2600000,
    placementHighest: 72000000,
    courses: ['B.Tech', 'M.Tech', 'MSc', 'MBA', 'PhD'],
    overview: 'IIT Delhi is a premier engineering institute with a legacy of academic excellence and innovation. Known for its strong industry connections and outstanding placement record.',
    image: '/images/colleges/iit-delhi.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:IIT Delhi Main Building 2022.jpg by TheVyomanaut (CC BY-SA 4.0)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1961,
    ranking: { nirf: 2, outlook: 2, times: 1, collegedunia: 3 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Health Center', 'Research Labs', 'Entrepreneurship Cell'],
    contact: { phone: '+91-11-26597135', email: 'info@iitd.ac.in', website: 'iitd.ac.in' },
    topRecruiters: ['Google', 'Amazon', 'Microsoft', 'Flipkart', 'Goldman Sachs', 'HUL', 'P&G', 'Texas Instruments'],
    campusSize: '320 acres',
    totalStudents: 9900,
    facultyCount: 700,
    accreditation: 'NAAC A++',
    hostelFees: '₹1,05,000/year',
    courseFees: [
      { name: 'B.Tech', totalFees: '₹8,40,000', duration: '4 Years' },
      { name: 'M.Tech', totalFees: '₹2,80,000', duration: '2 Years' },
      { name: 'MBA', totalFees: '₹11,60,000', duration: '2 Years' },
      { name: 'PhD', totalFees: '₹1,50,000', duration: '5 Years' },
    ],
    importantDates: [
      { event: 'JEE Advanced Application', date: 'April 2026' },
      { event: 'JEE Advanced Exam', date: 'May 2026' },
      { event: 'Counselling Start', date: 'June 2026' },
      { event: 'Classes Begin', date: 'July 2026' },
    ],
    annualEvents: ['Tryst', 'Rendezvous', 'Invasion'],
    notableAlumni: ['Dr. Rajendra Singh (Ramon Magsaysay Awardee)', 'Saurabh Chandra (IAS)', 'Pankaj Patel (Ex-Zydus Chairman)'],
  },
  {
    id: 'iit-madras',
    name: 'IIT Madras',
    location: 'Sardar Patel Road, Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    fees: 205000,
    rating: 4.8,
    placementRate: 91,
    placementAverage: 2400000,
    placementHighest: 70000000,
    courses: ['B.Tech', 'M.Tech', 'MSc', 'PhD'],
    overview: 'IIT Madras is a leading technical institute known for its research output and academic rigor. Consistently ranked #1 in NIRF rankings.',
    image: '/images/colleges/iit-madras.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Iit Madras campus (CC BY-SA)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1959,
    ranking: { nirf: 1, outlook: 4, times: 3, collegedunia: 4 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Tech Park'],
    contact: { phone: '+91-44-22578000', email: 'info@iitm.ac.in', website: 'iitm.ac.in' },
    topRecruiters: ['Google', 'Amazon', 'Microsoft', 'Intel', 'Qualcomm', 'Cisco', 'Oracle', 'Adobe'],
    campusSize: '620 acres',
    totalStudents: 8500,
    facultyCount: 680,
    accreditation: 'NAAC A++',
    hostelFees: '₹1,00,000/year',
    courseFees: [
      { name: 'B.Tech', totalFees: '₹8,20,000', duration: '4 Years' },
      { name: 'M.Tech', totalFees: '₹2,60,000', duration: '2 Years' },
      { name: 'MSc', totalFees: '₹1,50,000', duration: '2 Years' },
      { name: 'PhD', totalFees: '₹1,20,000', duration: '5 Years' },
    ],
    importantDates: [
      { event: 'JEE Advanced Application', date: 'April 2026' },
      { event: 'JEE Advanced Exam', date: 'May 2026' },
      { event: 'Counselling Start', date: 'June 2026' },
      { event: 'Classes Begin', date: 'July 2026' },
    ],
    annualEvents: ['Shaastra', 'Saarang', 'Tech Runway'],
    notableAlumni: ['K. Sivan (Ex-ISRO Chairman)', 'C. P. Krishnan Nair (Air India)', 'K. V. Kamath (ICICI Bank)'],
  },
  {
    id: 'bhu-varanasi',
    name: 'Banaras Hindu University',
    location: 'Varanasi',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    fees: 40000,
    rating: 4.4,
    placementRate: 70,
    placementAverage: 800000,
    placementHighest: 25000000,
    courses: ['B.Tech', 'BSc', 'BA', 'MSc', 'MBA', 'MA'],
    overview: 'BHU is a large central university offering a broad range of programs across sciences, arts, and engineering with a strong legacy of academic excellence.',
    image: '/images/colleges/bhu-varanasi.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Bhu Varanasi campus (CC BY-SA)",
    type: 'Central',
    approval: ['UGC', 'MHRD', 'NAAC A+'],
    established: 1916,
    ranking: { nirf: 12, outlook: 15, collegedunia: 8 },
    facilities: ['Central Library', 'Sports Stadium', 'Hostels', 'University Hospital', 'Research Centers', 'Museum'],
    contact: { phone: '+91-542-6700000', email: 'info@bhu.ac.in', website: 'bhu.ac.in' },
    topRecruiters: ['Amazon', 'TCS', 'Infosys', 'Wipro', 'HCL', 'Bajaj', 'ICICI Bank'],
    campusSize: '1300 acres',
    totalStudents: 30000,
    facultyCount: 1800,
    accreditation: 'NAAC A+',
    hostelFees: '₹25,000/year',
    courseFees: [
      { name: 'B.Tech', totalFees: '₹3,60,000', duration: '4 Years' },
      { name: 'MBA', totalFees: '₹2,40,000', duration: '2 Years' },
      { name: 'BA', totalFees: '₹32,000', duration: '3 Years' },
      { name: 'MSc', totalFees: '₹60,000', duration: '2 Years' },
    ],
    importantDates: [
      { event: 'CUET Application', date: 'March-April 2026' },
      { event: 'CUET Exam', date: 'May 2026' },
      { event: 'Counselling Start', date: 'July 2026' },
      { event: 'Classes Begin', date: 'August 2026' },
    ],
    annualEvents: ['Spandan', 'Uday', 'Kashi Utsav'],
    notableAlumni: ['Dr. APJ Abdul Kalam (Former President)', 'Narendra Modi (Honorary Degree)', 'Nikhil Kumar (Ex-Governor)'],
  },
  {
    id: 'iiit-hyderabad',
    name: 'IIIT Hyderabad',
    location: 'Gachibowli, Hyderabad',
    city: 'Hyderabad',
    state: 'Telangana',
    fees: 220000,
    rating: 4.8,
    placementRate: 90,
    placementAverage: 2800000,
    placementHighest: 65000000,
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    overview: 'International Institute of Information Technology, Hyderabad is a top-tier institute for computer science and research with stellar placements in top tech companies.',
    image: '/images/colleges/iiit-hyderabad.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Vindhya C4 building inside IIIT-H Campus, Hyderabad, Telengana.jpg by Amitabha Gupta (CC BY 4.0)",
    type: 'Deemed',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1998,
    ranking: { nirf: 20, outlook: 18, collegedunia: 6 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Incubation Center'],
    contact: { phone: '+91-40-66531000', email: 'info@iiit.ac.in', website: 'iiit.ac.in' },
    topRecruiters: ['Google', 'Microsoft', 'Amazon', 'Facebook', 'Twitter', 'Uber', 'Adobe', 'Nvidia'],
    campusSize: '62 acres',
    totalStudents: 3000,
    facultyCount: 200,
    accreditation: 'NAAC A++',
    hostelFees: '₹80,000/year',
    courseFees: [
      { name: 'B.Tech CSE', totalFees: '₹8,80,000', duration: '4 Years' },
      { name: 'B.Tech ECE', totalFees: '₹8,80,000', duration: '4 Years' },
      { name: 'M.Tech CSE', totalFees: '₹3,20,000', duration: '2 Years' },
      { name: 'PhD', totalFees: '₹1,60,000', duration: '5 Years' },
    ],
    importantDates: [
      { event: 'IIITH UG Application', date: 'April 2026' },
      { event: 'IIITH UGEE Exam', date: 'May 2026' },
      { event: 'Interview Round', date: 'June 2026' },
      { event: 'Classes Begin', date: 'July 2026' },
    ],
    annualEvents: ['Felicity', 'TechFiesta', 'E-Cell Summit'],
    notableAlumni: ['Srikanth Nadhamuni (Aadhaar Architect)', 'Sanjay Jha (GlobalFoundries)', 'Rohit Bhat (Talentica)'],
  },
  {
    id: 'kiet-ghaziabad',
    name: 'KIET Group of Institutions',
    location: 'Ghaziabad',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh',
    fees: 120000,
    rating: 4.0,
    placementRate: 78,
    placementAverage: 600000,
    placementHighest: 45000000,
    courses: ['B.Tech', 'MBA', 'MCA'],
    overview: 'KIET is a well-established private engineering college in Ghaziabad with a wide range of technical and professional programs and a strong industry interface.',
    image: '/images/colleges/kiet-ghaziabad.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Kiet ground.jpg by Navendu delhi (CC BY-SA 3.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A'],
    established: 1998,
    ranking: { nirf: 180, collegedunia: 45 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Cafeteria', 'Transport', 'Auditorium'],
  },
  {
    id: 'amity-noida',
    name: 'Amity University, Noida',
    location: 'Sector 125, Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    fees: 350000,
    rating: 3.9,
    placementRate: 65,
    placementAverage: 700000,
    placementHighest: 35000000,
    courses: ['B.Tech', 'BBA', 'MBA', 'Law', 'BA', 'BSc'],
    overview: 'Amity is a private university offering a broad spectrum of professional programs with extensive campus facilities and industry tie-ups across multiple disciplines.',
    image: '/images/colleges/amity-noida.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Amity University, Campus Noida.jpg by Hghulam49 (CC BY 4.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A+'],
    established: 2005,
    ranking: { nirf: 80, collegedunia: 25 },
    facilities: ['Central Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Auditorium', 'Wi-Fi Campus'],
  },
  {
    id: 'christ-bangalore',
    name: 'Christ University',
    location: 'Bengaluru',
    city: 'Bengaluru',
    state: 'Karnataka',
    fees: 90000,
    rating: 4.2,
    placementRate: 72,
    placementAverage: 650000,
    placementHighest: 30000000,
    courses: ['BBA', 'BSc', 'BCA', 'MBA', 'BA'],
    overview: 'Christ University is a popular private university known for its commerce and management programs and active placement cell with strong corporate connections.',
    image: '/images/colleges/christ-bangalore.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Christ University buildings, Bangalore 06.jpg by Pinakpani (CC BY-SA 4.0)",
    type: 'Private',
    approval: ['UGC', 'NAAC A+'],
    established: 1969,
    ranking: { nirf: 90, collegedunia: 30 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Auditorium', 'IT Infrastructure'],
  },
  {
    id: 'mnnit-prayagraj',
    name: 'MNNIT Allahabad',
    location: 'Prayagraj',
    city: 'Prayagraj',
    state: 'Uttar Pradesh',
    fees: 90000,
    rating: 4.2,
    placementRate: 82,
    placementAverage: 900000,
    placementHighest: 42000000,
    courses: ['B.Tech', 'M.Tech', 'PhD'],
    overview: 'Motilal Nehru National Institute of Technology (MNNIT) is a reputed NIT with strong engineering programs and consistent placement outcomes with top recruiters.',
    image: '/images/colleges/mnnit-prayagraj.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Mainbuildingnew.jpg by Undertaker2512 (Public domain)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1961,
    ranking: { nirf: 50, collegedunia: 15 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Health Center', 'Research Labs'],
  },
  {
    id: 'lpu-punjab',
    name: 'Lovely Professional University',
    location: 'Jalandhar',
    city: 'Jalandhar',
    state: 'Punjab',
    fees: 160000,
    rating: 4.1,
    placementRate: 75,
    placementAverage: 550000,
    placementHighest: 42000000,
    courses: ['B.Tech', 'MBA', 'BA', 'BSc', 'BCA', 'LLB', 'BBA'],
    overview: 'LPU is one of India\'s largest private universities with a sprawling campus and diverse programs. Known for its strong placement record with national and international companies.',
    image: '/images/colleges/lpu-punjab.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Admission-block-copy.jpg by Tanya2016 (CC BY-SA 4.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A++', 'BCI', 'PCI'],
    established: 2005,
    ranking: { nirf: 49, outlook: 18, collegedunia: 11 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Incubation Center', 'Mega Auditorium', 'Shopping Complex'],
  },
  {
    id: 'chandigarh-university',
    name: 'Chandigarh University',
    location: 'Mohali',
    city: 'Mohali',
    state: 'Punjab',
    fees: 175000,
    rating: 4.3,
    placementRate: 80,
    placementAverage: 700000,
    placementHighest: 47000000,
    courses: ['B.Tech', 'MBA', 'BBA', 'BCA', 'BA', 'BSc', 'LLB'],
    overview: 'Chandigarh University is a leading private university known for its excellent placement record, industry-oriented curriculum, and modern infrastructure.',
    image: '/images/colleges/chandigarh-university.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Main Block Chandigarh University.jpg by Navyison (CC BY-SA 4.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A+'],
    established: 2012,
    ranking: { nirf: 54, collegedunia: 14 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Incubation Center', 'Smart Classrooms'],
  },
  {
    id: 'bits-pilani',
    name: 'BITS Pilani',
    location: 'Pilani',
    city: 'Pilani',
    state: 'Rajasthan',
    fees: 450000,
    rating: 4.7,
    placementRate: 95,
    placementAverage: 2200000,
    placementHighest: 55000000,
    courses: ['B.Tech', 'M.Tech', 'MBA', 'MSc', 'PhD'],
    overview: 'Birla Institute of Technology and Science, Pilani is a premier private institute known for its rigorous academics, excellent placements, and vibrant campus life.',
    image: '/images/colleges/bits-pilani.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:BITS-Pilani campus aerial view.jpg (CC BY-SA 3.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A+'],
    established: 1964,
    ranking: { nirf: 25, outlook: 10, collegedunia: 5 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Innovation Center'],
  },
  {
    id: 'nit-trichy',
    name: 'NIT Trichy',
    location: 'Tiruchirappalli',
    city: 'Tiruchirappalli',
    state: 'Tamil Nadu',
    fees: 95000,
    rating: 4.6,
    placementRate: 88,
    placementAverage: 1800000,
    placementHighest: 52000000,
    courses: ['B.Tech', 'M.Tech', 'MCA', 'PhD'],
    overview: 'National Institute of Technology Tiruchirappalli is among the top NITs in India with excellent placement records and a strong alumni network.',
    image: '/images/colleges/nit-trichy.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Clock Tower NITT.jpg by Leelmbar092 (CC BY-SA 4.0)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1964,
    ranking: { nirf: 23, outlook: 12, collegedunia: 7 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs'],
  },
  {
    id: 'srcc-delhi',
    name: 'Shri Ram College of Commerce',
    location: 'Delhi',
    city: 'Delhi',
    state: 'Delhi',
    fees: 25000,
    rating: 4.8,
    placementRate: 85,
    placementAverage: 1500000,
    placementHighest: 35000000,
    courses: ['B.Com (Hons)', 'BA (Hons) Economics', 'M.Com'],
    overview: 'SRCC is India\'s premier commerce college and a part of Delhi University. Known for producing top business leaders and consistently ranking #1 in commerce education.',
    image: '/images/colleges/srcc-delhi.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:College Full view-1.jpg by RatedH2k (CC BY-SA 4.0)",
    type: 'Government',
    approval: ['UGC', 'NAAC A+'],
    established: 1926,
    ranking: { nirf: 1, collegedunia: 1 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Auditorium', 'Computer Lab'],
  },
  {
    id: 'iim-ahmedabad',
    name: 'IIM Ahmedabad',
    location: 'Vastrapur, Ahmedabad',
    city: 'Ahmedabad',
    state: 'Gujarat',
    fees: 2400000,
    rating: 4.9,
    placementRate: 100,
    placementAverage: 35000000,
    placementHighest: 120000000,
    courses: ['MBA', 'PGDM', 'FPM', 'ePGP'],
    overview: 'IIM Ahmedabad is India\'s premier management institute, consistently ranked #1. Known for its rigorous academic curriculum, world-class faculty, and stellar placements.',
    image: '/images/colleges/iim-ahmedabad.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Louis Kahn Plaza, IIM Ahmedabad.jpg by Perspectives - The Photography Club, IIM Ahmedabad (CC BY-SA 4.0)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1961,
    ranking: { nirf: 1, outlook: 1, times: 1, collegedunia: 1 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Centers', 'Executive Education Center'],
  },
  {
    id: 'du-stephans',
    name: 'St. Stephen\'s College',
    location: 'Delhi',
    city: 'Delhi',
    state: 'Delhi',
    fees: 25000,
    rating: 4.6,
    placementRate: 55,
    placementAverage: 800000,
    placementHighest: 20000000,
    courses: ['BA', 'BSc', 'BCom'],
    overview: 'St. Stephen\'s is one of India\'s top liberal arts colleges with a strong academic reputation and distinguished alumni network spanning across the globe.',
    image: '/images/colleges/du-stephans.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:St- Stephens.jpg by H CHRYSO (CC BY-SA 4.0)",
    type: 'Government',
    approval: ['UGC', 'NAAC A+'],
    established: 1881,
    ranking: { nirf: 18, collegedunia: 10 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Chapel', 'Auditorium'],
  },
  {
    id: 'vit-vellore',
    name: 'VIT Vellore',
    location: 'Vellore',
    city: 'Vellore',
    state: 'Tamil Nadu',
    fees: 180000,
    rating: 4.4,
    placementRate: 85,
    placementAverage: 800000,
    placementHighest: 39000000,
    courses: ['B.Tech', 'M.Tech', 'MBA', 'MCA', 'PhD'],
    overview: 'VIT Vellore is a leading private engineering institution known for its world-class infrastructure, research output, and excellent placement opportunities.',
    image: '/images/colleges/vit-vellore.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Technology Tower(VIT).jpg by Wikindinator (CC BY-SA 3.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A++'],
    established: 1984,
    ranking: { nirf: 32, outlook: 15, collegedunia: 9 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Technology Tower'],
  },
  {
    id: 'jnu-delhi',
    name: 'Jawaharlal Nehru University',
    location: 'New Delhi',
    city: 'Delhi',
    state: 'Delhi',
    fees: 15000,
    rating: 4.5,
    placementRate: 60,
    placementAverage: 600000,
    placementHighest: 22000000,
    courses: ['BA', 'MA', 'MSc', 'MBA', 'PhD'],
    overview: 'JNU is a premier central university known for its academic excellence, research output, and vibrant campus culture. Consistently ranked among the top universities in India.',
    image: '/images/colleges/jnu-delhi.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:JNU Admin.JPG by Ganga Sahay Meena (CC BY-SA 3.0)",
    type: 'Central',
    approval: ['UGC', 'NAAC A++'],
    established: 1969,
    ranking: { nirf: 2, collegedunia: 3 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Health Center', 'Research Centers', 'Convention Center'],
  },
  {
    id: 'symbiosis-pune',
    name: 'Symbiosis International University',
    location: 'Pune',
    city: 'Pune',
    state: 'Maharashtra',
    fees: 350000,
    rating: 4.3,
    placementRate: 78,
    placementAverage: 1200000,
    placementHighest: 35000000,
    courses: ['MBA', 'BBA', 'BA', 'BSc', 'LLB', 'B.Tech'],
    overview: 'Symbiosis is a leading deemed university in Pune known for its diverse programs, international collaborations, and excellent placement record across all disciplines.',
    image: '/images/colleges/symbiosis-pune.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Symbiosis International University, S. B. Road campus.jpg by DesiBoy101 (CC BY 4.0)",
    type: 'Deemed',
    approval: ['UGC', 'NAAC A+', 'AICTE'],
    established: 1971,
    ranking: { nirf: 35, collegedunia: 16 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'International Student Center'],
  },
  {
    id: 'manipal-university',
    name: 'Manipal Academy of Higher Education',
    location: 'Manipal',
    city: 'Manipal',
    state: 'Karnataka',
    fees: 400000,
    rating: 4.4,
    placementRate: 82,
    placementAverage: 1000000,
    placementHighest: 38000000,
    courses: ['MBBS', 'B.Tech', 'MBA', 'BSc', 'MSc', 'PhD'],
    overview: 'MAHE Manipal is a premier deemed university offering world-class education across medical, engineering, management, and humanities disciplines with global recognition.',
    image: '/images/colleges/manipal-university.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Manipal Institute of Technology Academic Building, Manipal University, Manipal Campus, India (Ank Kumar, Infosys Limited) 01.jpg by Ank Kumar (CC BY-SA 4.0)",
    type: 'Deemed',
    approval: ['UGC', 'NAAC A++', 'MCI', 'AICTE'],
    established: 1953,
    ranking: { nirf: 40, collegedunia: 20 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'University Hospital', 'Research Labs', 'International Center'],
  },
  {
    id: 'jadavpur-university',
    name: 'Jadavpur University',
    location: 'Kolkata',
    city: 'Kolkata',
    state: 'West Bengal',
    fees: 12000,
    rating: 4.5,
    placementRate: 76,
    placementAverage: 900000,
    placementHighest: 32000000,
    courses: ['B.Tech', 'BA', 'BSc', 'MBA', 'MA', 'PhD'],
    overview: 'Jadavpur University is a premier state university known for its strong engineering and arts programs. One of the oldest and most respected institutions in India.',
    image: '/images/colleges/jadavpur-university.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Aurobindo Bhavan - Main Administrative Building - Jadavpur University - Kolkata 2015-01-08 2401.JPG by Biswarup Ganguly (CC BY 3.0)",
    type: 'Government',
    approval: ['UGC', 'NAAC A+', 'AICTE'],
    established: 1955,
    ranking: { nirf: 15, collegedunia: 12 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Health Center', 'Research Labs'],
  },
  {
    id: 'amrita-university',
    name: 'Amrita Vishwa Vidyapeetham',
    location: 'Coimbatore',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    fees: 250000,
    rating: 4.4,
    placementRate: 84,
    placementAverage: 900000,
    placementHighest: 42000000,
    courses: ['B.Tech', 'MBA', 'MBBS', 'BSc', 'MSc', 'PhD'],
    overview: 'Amrita University is a multi-campus deemed university known for its emphasis on research, value-based education, and strong placement record across disciplines.',
    image: '/images/colleges/amrita-university.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Amrita Vishwa Vidyapeetham coimbatore campus.jpg by Manhardas in (CC BY-SA 4.0)",
    type: 'Deemed',
    approval: ['UGC', 'NAAC A++', 'AICTE', 'MCI'],
    established: 1994,
    ranking: { nirf: 7, collegedunia: 10 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'University Hospital', 'Research Centers', 'Temple'],
  },
  {
    id: 'dtu-delhi',
    name: 'Delhi Technological University',
    location: 'Shahbad Daulatpur, Delhi',
    city: 'Delhi',
    state: 'Delhi',
    fees: 95000,
    rating: 4.3,
    placementRate: 86,
    placementAverage: 1200000,
    placementHighest: 48000000,
    courses: ['B.Tech', 'M.Tech', 'MBA', 'PhD'],
    overview: 'DTU is one of India\'s leading engineering universities known for its strong industry connections, excellent placement record, and innovative academic programs.',
    image: '/images/colleges/dtu-delhi.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Entrance Gate of Delhi Technological University.jpeg by Maskaravivek (CC BY 3.0)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1941,
    ranking: { nirf: 48, collegedunia: 18 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Incubation Center'],
  },
  {
    id: 'hindu-college',
    name: 'Hindu College',
    location: 'Delhi',
    city: 'Delhi',
    state: 'Delhi',
    fees: 22000,
    rating: 4.7,
    placementRate: 65,
    placementAverage: 700000,
    placementHighest: 18000000,
    courses: ['BA', 'BSc', 'BCom', 'MA'],
    overview: 'Hindu College, University of Delhi, is one of India\'s most prestigious colleges known for academic excellence, distinguished faculty, and a vibrant cultural scene.',
    image: '/images/colleges/hindu-college.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Hindu College (Front).jpg (CC BY-SA 4.0)",
    type: 'Government',
    approval: ['UGC', 'NAAC A+'],
    established: 1899,
    ranking: { nirf: 1, collegedunia: 2 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Auditorium', 'Computer Lab', 'Botanical Garden'],
  },
  {
    id: 'nsut-delhi',
    name: 'Netaji Subhas University of Technology',
    location: 'Dwarka, Delhi',
    city: 'Delhi',
    state: 'Delhi',
    fees: 90000,
    rating: 4.2,
    placementRate: 83,
    placementAverage: 1100000,
    placementHighest: 45000000,
    courses: ['B.Tech', 'M.Tech', 'MBA', 'PhD'],
    overview: 'NSUT (formerly NSIT) is a premier engineering university in Delhi known for its excellent academic programs, industry partnerships, and outstanding placements.',
    image: '/images/colleges/nsut-delhi.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Central Library NSIT (Dwarka).jpg by Bogas04 (CC BY-SA 3.0)",
    type: 'Government',
    approval: ['AICTE', 'UGC', 'MHRD'],
    established: 1983,
    ranking: { nirf: 60, collegedunia: 22 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs'],
  },
  {
    id: 'thapar-university',
    name: 'Thapar Institute of Engineering & Technology',
    location: 'Patiala',
    city: 'Patiala',
    state: 'Punjab',
    fees: 220000,
    rating: 4.1,
    placementRate: 80,
    placementAverage: 850000,
    placementHighest: 38000000,
    courses: ['B.Tech', 'M.Tech', 'MBA', 'MCA', 'PhD'],
    overview: 'Thapar Institute is a prestigious private engineering institution with a strong emphasis on research, innovation, and industry-prepared graduates.',
    image: '/images/colleges/thapar-university.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Thapar Campus Aerial View.jpg by Ayush.undefined (CC BY-SA 3.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A+'],
    established: 1956,
    ranking: { nirf: 55, collegedunia: 23 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Technology Park'],
  },
  {
    id: 'srm-university',
    name: 'SRM Institute of Science and Technology',
    location: 'Chennai',
    city: 'Chennai',
    state: 'Tamil Nadu',
    fees: 250000,
    rating: 4.0,
    placementRate: 78,
    placementAverage: 700000,
    placementHighest: 42000000,
    courses: ['B.Tech', 'M.Tech', 'MBA', 'MBBS', 'BSc', 'PhD'],
    overview: 'SRM is one of India\'s largest private universities with a global outlook, modern infrastructure, and strong placement connections across multiple sectors.',
    image: '/images/colleges/srm-university.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:SRM University Auditorium.JPG by Hareesh Sivasubramanian (CC BY-SA 3.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A++', 'MCI'],
    established: 1985,
    ranking: { nirf: 42, collegedunia: 17 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Technology Park'],
  },
  {
    id: 'pict-pune',
    name: 'Pune Institute of Computer Technology',
    location: 'Pune',
    city: 'Pune',
    state: 'Maharashtra',
    fees: 130000,
    rating: 4.3,
    placementRate: 87,
    placementAverage: 950000,
    placementHighest: 40000000,
    courses: ['B.Tech', 'M.Tech'],
    overview: 'PICT is a leading private engineering college in Pune known for its excellent computer science education and strong placement record in top IT companies.',
    image: '/images/colleges/pict-pune.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Pune Institute of Computer Technology, Katraj, Pune.jpg by Niraj Suryawanshi (CC BY-SA 3.0)",
    type: 'Private',
    approval: ['AICTE', 'NAAC A'],
    established: 1983,
    ranking: { collegedunia: 28 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Cafeteria', 'Research Labs'],
  },
  {
    id: 'rv-bangalore',
    name: 'RV College of Engineering',
    location: 'Bengaluru',
    city: 'Bengaluru',
    state: 'Karnataka',
    fees: 200000,
    rating: 4.4,
    placementRate: 89,
    placementAverage: 1000000,
    placementHighest: 45000000,
    courses: ['B.Tech', 'M.Tech', 'MBA', 'PhD'],
    overview: 'RVCE is one of the top private engineering colleges in India, known for its excellent academic standards, research output, and outstanding placements.',
    image: '/images/colleges/rv-bangalore.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:RV College Admin block.JPG by Rvian00 (CC BY-SA 3.0)",
    type: 'Private',
    approval: ['AICTE', 'UGC', 'NAAC A+'],
    established: 1963,
    ranking: { nirf: 58, collegedunia: 21 },
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Medical Center', 'Research Labs', 'Incubation Center'],
  },
  {
    id: 'aligarh-muslim-university',
    name: 'Aligarh Muslim University',
    location: 'Aligarh',
    city: 'Aligarh',
    state: 'Uttar Pradesh',
    fees: 35000,
    rating: 4.1,
    placementRate: 60,
    placementAverage: 500000,
    placementHighest: 18000000,
    courses: ['BA', 'BSc', 'B.Tech', 'MBA', 'MA', 'LLB'],
    overview: 'AMU is a historic central university offering strong arts and science programs and selected professional courses with a rich campus culture and distinguished alumni.',
    image: '/images/colleges/aligarh-muslim-university.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Arts Faculty - panoramio.jpg by yousufnet (CC BY 3.0)",
    type: 'Central',
    approval: ['UGC', 'MHRD', 'NAAC A+'],
    established: 1875,
    ranking: { nirf: 30, collegedunia: 20 },
    facilities: ['Central Library', 'Sports Complex', 'Hostels', 'University Hospital', 'Research Centers', 'Museum'],
    contact: { phone: '+91-571-2700920', email: 'info@amu.ac.in', website: 'amu.ac.in' },
  },
  {
    id: 'jmi-delhi',
    name: 'Jamia Millia Islamia',
    location: 'New Delhi',
    city: 'Delhi',
    state: 'Delhi',
    fees: 30000,
    rating: 4.0,
    placementRate: 58,
    placementAverage: 600000,
    placementHighest: 22000000,
    courses: ['B.Tech', 'BA', 'MBA', 'MA', 'BSc', 'LLB'],
    overview: 'Jamia is a central university offering diverse academic programs and steadily improving placement support for professional courses across multiple disciplines.',
    image: '/images/colleges/jmi-delhi.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:Centenary Gate of Jamia Millia Islamia.jpg by Redmyname31 (CC BY-SA 4.0)",
    type: 'Central',
    approval: ['UGC', 'MHRD', 'NAAC A+'],
    established: 1920,
    ranking: { nirf: 28, collegedunia: 18 },
    facilities: ['Central Library', 'Sports Complex', 'Hostels', 'Health Center', 'Research Centers', 'Auditorium'],
    contact: { phone: '+91-11-26981717', email: 'info@jmi.ac.in', website: 'jmi.ac.in' },
  },
  {
    id: 'iet-lucknow',
    name: 'Institute of Engineering & Technology, Lucknow',
    location: 'Lucknow',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    fees: 80000,
    rating: 3.8,
    placementRate: 68,
    placementAverage: 550000,
    placementHighest: 28000000,
    courses: ['B.Tech', 'M.Tech'],
    overview: 'IET Lucknow is known for solid undergraduate engineering programs and a growing ecosystem for placements and internships in emerging technologies.',
    image: '/images/colleges/iet-lucknow.jpg',
    imageSource: "Wikimedia Commons",
    imageAttribution: "File:IET college Lucknow.jpg by Vujn (Public domain)",
    type: 'Government',
    approval: ['AICTE', 'UGC'],
    established: 1984,
    ranking: { collegedunia: 35 },
    facilities: ['Library', 'Sports Ground', 'Hostels', 'Cafeteria', 'Computer Labs', 'Workshops'],
  },
  {
    id: 'navrachana-vadodara',
    name: 'Navrachana University',
    location: 'Vadodara',
    city: 'Vadodara',
    state: 'Gujarat',
    fees: 110000,
    rating: 3.7,
    placementRate: 50,
    placementAverage: 400000,
    placementHighest: 15000000,
    courses: ['B.Tech', 'Design', 'MBA', 'BSc'],
    overview: 'Navrachana is a private university focused on multidisciplinary programs and experiential learning with emerging placement services and industry connections.',
    image: '/images/colleges/navrachana-vadodara.svg',
    imageSource: "Placeholder",
    imageAttribution: "No verified real campus photo found (generated placeholder graphic)",
    type: 'Private',
    approval: ['UGC', 'NAAC B+'],
    established: 2009,
    ranking: {},
    facilities: ['Library', 'Sports Complex', 'Hostels', 'Cafeteria', 'Design Studio', 'Computer Labs'],
  },
]

// Backward compatibility alias map: old IDs that redirect to current IDs
export const collegeAliasMap: Record<string, string> = {
  'ststephen-delhi': 'du-stephans',
  'amnit-prayagraj': 'mnnit-prayagraj',
  'amit-prayagraj': 'mnnit-prayagraj',
}

/** Resolve a slug/ID, handling aliases */
export function resolveCollegeSlug(slug: string): string {
  return collegeAliasMap[slug] || slug
}

export function getCollegeBySlug(slug: string): College | undefined {
  const resolved = resolveCollegeSlug(slug)
  return colleges.find(c => c.id === resolved)
}

export const getCollegeById = (id: string): College | undefined => colleges.find(c => c.id === id)

export const getCollegesByFilters = (params: {
  query?: string
  location?: string
  state?: string
  course?: string
  type?: string
  minFees?: number
  maxFees?: number
  minRating?: number
  minPlacement?: number
  sortBy?: 'fees' | 'rating' | 'placementRate' | 'name'
  sortOrder?: 'asc' | 'desc'
  page?: number
  limit?: number
}) => {
  let results = [...colleges]

  if (params.query) {
    const q = params.query.toLowerCase()
    results = results.filter(
      c =>
        c.name.toLowerCase().includes(q) ||
        c.location.toLowerCase().includes(q) ||
        c.city.toLowerCase().includes(q) ||
        c.state.toLowerCase().includes(q) ||
        c.courses.some(course => course.toLowerCase().includes(q)) ||
        c.overview.toLowerCase().includes(q)
    )
  }

  if (params.location) results = results.filter(c => c.location.toLowerCase().includes(params.location!.toLowerCase()))
  if (params.state) results = results.filter(c => c.state.toLowerCase() === params.state!.toLowerCase())
  if (params.course) results = results.filter(c => c.courses.some(cr => cr.toLowerCase().includes(params.course!.toLowerCase())))
  if (params.type) results = results.filter(c => c.type.toLowerCase() === params.type!.toLowerCase())
  if (params.minFees) results = results.filter(c => c.fees >= params.minFees!)
  if (params.maxFees) results = results.filter(c => c.fees <= params.maxFees!)
  if (params.minRating) results = results.filter(c => c.rating >= params.minRating!)
  if (params.minPlacement) results = results.filter(c => c.placementRate >= params.minPlacement!)

  if (params.sortBy) {
    results.sort((a, b) => {
      const multiplier = params.sortOrder === 'desc' ? -1 : 1
      const aVal = a[params.sortBy!] ?? 0
      const bVal = b[params.sortBy!] ?? 0
      if (typeof aVal === 'string') return (aVal as string).localeCompare(bVal as string) * multiplier
      return ((aVal as number) - (bVal as number)) * multiplier
    })
  }

  const page = params.page || 1
  const limit = params.limit || 20
  const total = results.length
  const totalPages = Math.ceil(total / limit)
  const paginated = results.slice((page - 1) * limit, page * limit)

  return { colleges: paginated, total, totalPages, page }
}

export const predictColleges = (input: {
  exam: string
  rank: number
  score: number
  category: string
  state: string
  course: string
  collegeTypePreference?: string
  maxFees?: number
}) => {
  const categoryMultipliers: Record<string, number> = {
    'General': 1,
    'OBC': 1.25,
    'SC': 2.5,
    'ST': 3.0,
    'EWS': 1.5,
  }
  const multiplier = categoryMultipliers[input.category] || 1
  const effectiveRank = input.rank / multiplier
  const feeLimit = input.maxFees ? input.maxFees * 100000 : Infinity

  const results = colleges
    .filter((college) => {
      if (input.maxFees && college.fees > feeLimit) return false
      if (input.collegeTypePreference && input.collegeTypePreference !== 'Any') {
        const pref = input.collegeTypePreference
        if (pref === 'IIT' && !college.id.startsWith('iit-')) return false
        if (pref === 'NIT' && !college.id.startsWith('nit-')) return false
        if (pref === 'Private' && college.type !== 'Private') return false
        if (pref === 'Deemed' && college.type !== 'Deemed') return false
        if (pref === 'State' && college.type !== 'Government') return false
      }
      return college.courses.some((cr) => cr.toLowerCase().includes(input.course.toLowerCase().split(' ')[0]))
    })
    .map((college) => {
      const baseScore = college.rating * 10 + college.placementRate / 10
      const rankFactor = Math.max(0, 1 - effectiveRank / 50000)
      const chance = Math.min(95, Math.max(5, Math.round(baseScore * rankFactor * 1.5)))

      const prevCutoff = college.cutoffs?.find((c) => c.exam.toLowerCase().includes(input.exam.toLowerCase().split(' ')[0]))

      return {
        college,
        chance,
        previousCutoff: prevCutoff?.score,
        difference: prevCutoff ? input.score - prevCutoff.score : undefined,
        category: input.category,
      }
    })
    .sort((a, b) => b.chance - a.chance)

  return results
}
