import { Exam, BlogPost, FAQ } from './types'

export const exams: Exam[] = [
  {
    id: 'jee-main',
    name: 'JEE Main',
    fullName: 'Joint Entrance Examination Main',
    level: 'National',
    date: 'April 2, 2026',
    applicationDate: 'Applications Open',
    participatingColleges: 2047,
    description: 'National level engineering entrance exam for admission to NITs, IIITs, and CFTIs.',
    icon: '🔬',
  },
  {
    id: 'jee-advanced',
    name: 'JEE Advanced',
    fullName: 'Joint Entrance Examination Advanced',
    level: 'National',
    date: 'May 17, 2026',
    applicationDate: 'Applications Open',
    participatingColleges: 33,
    description: 'Gateway to the prestigious Indian Institutes of Technology (IITs).',
    icon: '⚡',
  },
  {
    id: 'neet',
    name: 'NEET UG',
    fullName: 'National Eligibility cum Entrance Test',
    level: 'National',
    date: 'May 3, 2026',
    applicationDate: 'Applications Open',
    participatingColleges: 1374,
    description: 'Sole entrance exam for MBBS, BDS, and other medical courses in India.',
    icon: '🏥',
  },
  {
    id: 'cat',
    name: 'CAT',
    fullName: 'Common Admission Test',
    level: 'National',
    date: 'November 30, 2026',
    applicationDate: 'Applications Open',
    participatingColleges: 1781,
    description: 'Premier management entrance exam for admission to IIMs and top B-schools.',
    icon: '📊',
  },
  {
    id: 'cuet',
    name: 'CUET UG',
    fullName: 'Common University Entrance Test',
    level: 'National',
    date: 'May 11, 2026',
    applicationDate: 'Applications Open',
    participatingColleges: 583,
    description: 'Central university entrance exam for undergraduate programs across India.',
    icon: '🎓',
  },
  {
    id: 'gate',
    name: 'GATE',
    fullName: 'Graduate Aptitude Test in Engineering',
    level: 'National',
    date: 'February 7, 2026',
    applicationDate: 'Closed',
    participatingColleges: 894,
    description: 'Postgraduate engineering entrance exam for M.Tech and PSU recruitment.',
    icon: '🔧',
  },
  {
    id: 'cmat',
    name: 'CMAT',
    fullName: 'Common Management Admission Test',
    level: 'National',
    date: 'March 15, 2026',
    applicationDate: 'Applications Open',
    participatingColleges: 1520,
    description: 'Management entrance exam for admission to AICTE-approved MBA/PGDM programs.',
    icon: '📈',
  },
  {
    id: 'clat',
    name: 'CLAT',
    fullName: 'Common Law Admission Test',
    level: 'National',
    date: 'December 1, 2026',
    applicationDate: 'Applications Open',
    participatingColleges: 196,
    description: 'Central law entrance exam for admission to NLUs and other premier law colleges.',
    icon: '⚖️',
  },
]

export const blogPosts: BlogPost[] = [
  {
    id: 'blog-1',
    title: 'Top Engineering Colleges in India 2026: A Complete Guide',
    excerpt: 'Discover the best engineering colleges in India for 2026. Detailed analysis of IITs, NITs, and top private institutions with placement data.',
    image: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?w=600',
    date: 'June 12, 2026',
    category: 'Engineering',
    author: 'College Discovery Team',
    slug: 'top-engineering-colleges-2026',
  },
  {
    id: 'blog-2',
    title: 'JEE Main 2026: Complete Preparation Strategy and Study Plan',
    excerpt: 'A comprehensive 6-month study plan for JEE Main 2026. Covering syllabus, important topics, mock tests, and time management tips.',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=600',
    date: 'June 10, 2026',
    category: 'Exam Prep',
    author: 'College Discovery Team',
    slug: 'jee-main-2026-preparation',
  },
  {
    id: 'blog-3',
    title: 'MBA vs M.Tech: Which Career Path is Right for You?',
    excerpt: 'Compare MBA and M.Tech programs based on career prospects, salary potential, duration, and personal interests.',
    image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=600',
    date: 'June 8, 2026',
    category: 'Career Guidance',
    author: 'College Discovery Team',
    slug: 'mba-vs-mtech-career-guide',
  },
  {
    id: 'blog-4',
    title: 'NEET UG 2026: Latest Updates and Important Dates',
    excerpt: 'Stay updated with NEET UG 2026 exam dates, application process, syllabus changes, and preparation tips from toppers.',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600',
    date: 'June 6, 2026',
    category: 'Medical',
    author: 'College Discovery Team',
    slug: 'neet-ug-2026-updates',
  },
  {
    id: 'blog-5',
    title: 'How to Choose the Right College: A Step-by-Step Guide',
    excerpt: 'Learn how to evaluate colleges based on accreditation, placements, faculty, infrastructure, location, and return on investment.',
    image: 'https://images.unsplash.com/photo-1523050854058-8df90110c7f1?w=600',
    date: 'June 4, 2026',
    category: 'College Guide',
    author: 'College Discovery Team',
    slug: 'how-to-choose-right-college',
  },
  {
    id: 'blog-6',
    title: 'Top 10 High-Paying Career Options After 12th Science',
    excerpt: 'Explore the most lucrative career paths for science students including engineering, medicine, research, data science, and more.',
    image: 'https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=600',
    date: 'June 2, 2026',
    category: 'Career Guidance',
    author: 'College Discovery Team',
    slug: 'high-paying-careers-after-12th-science',
  },
]

export const faqs: FAQ[] = [
  {
    question: 'How does the college predictor work?',
    answer: 'Our college predictor uses your exam rank, category, and preferred course to estimate your admission chances. It analyzes historical cutoff data, category multipliers, and college ratings to calculate a percentage probability for each college.',
    category: 'Predictor',
  },
  {
    question: 'Is the information on this platform accurate?',
    answer: 'We strive to maintain the most up-to-date and accurate information. Our data is sourced from official college websites, government portals, and verified user reviews. However, we recommend confirming critical details with the respective institutions.',
    category: 'General',
  },
  {
    question: 'Can I compare more than 3 colleges?',
    answer: 'Currently, you can compare up to 3 colleges side-by-side. This limitation ensures the comparison table remains clear and easy to read. You can swap colleges anytime to compare different options.',
    category: 'Comparison',
  },
  {
    question: 'Is there a fee for using this platform?',
    answer: 'No, College Discovery is completely free for students. We provide college information, comparisons, and predictions at no cost. Our platform is supported by partnerships with educational institutions.',
    category: 'General',
  },
  {
    question: 'How are college ratings calculated?',
    answer: 'Our ratings are aggregated from multiple sources including NIRF rankings, student reviews, placement records, faculty quality, infrastructure, and academic reputation. Each factor is weighted to provide a balanced overall rating.',
    category: 'General',
  },
  {
    question: 'What should I consider when choosing a college?',
    answer: 'Key factors include accreditation, placement records, faculty qualifications, campus infrastructure, location, fees, scholarship opportunities, alumni network, and the specific course curriculum that matches your career goals.',
    category: 'College Guide',
  },
  {
    question: 'How often is the data updated?',
    answer: 'We update our database regularly with the latest information from official sources. Placement data, fees, and rankings are updated annually, while admission dates and cutoffs are updated in real-time during the admission season.',
    category: 'General',
  },
  {
    question: 'Can I save my favorite colleges?',
    answer: 'Yes, you can save colleges by clicking the "Save" button on any college card or detail page. Your saved colleges are stored locally and can be accessed from the dashboard for quick reference and comparison.',
    category: 'Dashboard',
  },
]
